language: python

python:
  - "3.4"

sudo: true

before_script:
  - pip install -r test-requirements.txt

script:
  - coala-ci
  - pytest --cov

after_success:
  - bash <(curl -s https://codecov.io/bash)
